/* Generated by mkguards.py */
package edu.lsu.cct.javalineer.functionalinterfaces;
import edu.lsu.cct.javalineer.Var;

@FunctionalInterface
public interface GuardTask3<T1, T2, T3> {
    void run(Var<T1> t1, Var<T2> t2, Var<T3> t3);
}

