/* Generated by mkguards.py */
package edu.lsu.cct.javalineer.functionalinterfaces;
import edu.lsu.cct.javalineer.Var;

@FunctionalInterface
public interface GuardTask8<T1, T2, T3, T4, T5, T6, T7, T8> {
    void run(Var<T1> t1, Var<T2> t2, Var<T3> t3, Var<T4> t4, Var<T5> t5, Var<T6> t6, Var<T7> t7, Var<T8> t8);
}

