/* Generated by mkguards.py */
package edu.lsu.cct.javalineer.functionalinterfaces;
import edu.lsu.cct.javalineer.Var;

import java.util.Optional;

@FunctionalInterface
public interface OptionalGuardTask13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> {
    void run(Optional<Var<T1>> o1, Optional<Var<T2>> o2, Optional<Var<T3>> o3, Optional<Var<T4>> o4, Optional<Var<T5>> o5, Optional<Var<T6>> o6, Optional<Var<T7>> o7, Optional<Var<T8>> o8, Optional<Var<T9>> o9, Optional<Var<T10>> o10, Optional<Var<T11>> o11, Optional<Var<T12>> o12, Optional<Var<T13>> o13);
}

