/* Generated by mkguards.py */
package edu.lsu.cct.javalineer.functionalinterfaces;
import edu.lsu.cct.javalineer.Var;

import java.util.Optional;

@FunctionalInterface
public interface OptionalGuardTask4<T1, T2, T3, T4> {
    void run(Optional<Var<T1>> o1, Optional<Var<T2>> o2, Optional<Var<T3>> o3, Optional<Var<T4>> o4);
}

